# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vending_machineIolNCZ.ui'
##
## Created by: Qt User Interface Compiler version 5.15.8
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(2080, 1300)
        Dialog.setMinimumSize(QSize(400, 0))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(220, 233, 237, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(237, 244, 246, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(110, 116, 118, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(147, 155, 158, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush7 = QBrush(QColor(0, 0, 0, 128))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush7)
#endif
        Dialog.setPalette(palette)
        self.calendarWidget = QCalendarWidget(Dialog)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(820, 130, 328, 311))
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 70, 511, 41))
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(130, 150, 68, 31))
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(130, 200, 68, 31))
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(130, 250, 68, 31))
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(130, 300, 68, 31))
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(130, 350, 68, 31))
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 400, 68, 31))
        self.label_8 = QLabel(Dialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(130, 450, 68, 31))
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 500, 68, 31))
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 550, 68, 31))
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(130, 600, 68, 31))
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(130, 650, 68, 31))
        self.pushButton = QPushButton(Dialog)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(210, 150, 99, 31))
        font = QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(False)
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(210, 200, 99, 31))
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.pushButton_2.setFont(font1)
        self.pushButton_3 = QPushButton(Dialog)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(210, 250, 99, 31))
        self.pushButton_3.setFont(font1)
        self.pushButton_4 = QPushButton(Dialog)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(210, 300, 99, 31))
        self.pushButton_4.setFont(font1)
        self.pushButton_5 = QPushButton(Dialog)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(210, 350, 99, 31))
        self.pushButton_5.setFont(font1)
        self.pushButton_6 = QPushButton(Dialog)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(210, 400, 99, 31))
        self.pushButton_6.setFont(font1)
        self.pushButton_7 = QPushButton(Dialog)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(210, 450, 99, 31))
        self.pushButton_7.setFont(font1)
        self.pushButton_8 = QPushButton(Dialog)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(210, 500, 99, 31))
        self.pushButton_8.setFont(font1)
        self.pushButton_9 = QPushButton(Dialog)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(210, 550, 99, 31))
        self.pushButton_9.setFont(font1)
        self.pushButton_10 = QPushButton(Dialog)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(210, 600, 99, 31))
        self.pushButton_10.setFont(font1)
        self.pushButton_11 = QPushButton(Dialog)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(210, 650, 99, 31))
        self.pushButton_11.setFont(font1)
        self.horizontalSlider = QSlider(Dialog)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(80, 720, 1161, 51))
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.dial = QDial(Dialog)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(980, 470, 231, 201))
        self.spinBox = QSpinBox(Dialog)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(490, 150, 111, 31))
        self.spinBox_2 = QSpinBox(Dialog)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(490, 200, 111, 31))
        self.spinBox_3 = QSpinBox(Dialog)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(490, 250, 111, 31))
        self.spinBox_4 = QSpinBox(Dialog)

        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(490, 300, 111, 31))
        self.spinBox_5 = QSpinBox(Dialog)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(490, 350, 111, 31))
        self.spinBox_6 = QSpinBox(Dialog)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(490, 400, 111, 31))
        self.spinBox_7 = QSpinBox(Dialog)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(490, 450, 111, 31))
        self.spinBox_8 = QSpinBox(Dialog)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setGeometry(QRect(490, 500, 111, 31))
        self.spinBox_9 = QSpinBox(Dialog)
        self.spinBox_9.setObjectName(u"spinBox_9")
        self.spinBox_9.setGeometry(QRect(490, 550, 111, 31))
        self.spinBox_10 = QSpinBox(Dialog)
        self.spinBox_10.setObjectName(u"spinBox_10")
        self.spinBox_10.setGeometry(QRect(490, 600, 111, 31))
        self.spinBox_11 = QSpinBox(Dialog)
        self.spinBox_11.setObjectName(u"spinBox_11")
        self.spinBox_11.setGeometry(QRect(490, 650, 111, 31))
        self.line_2 = QFrame(Dialog)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(100, 130, 571, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.pushButton_1_6 = QPushButton(Dialog)
        self.pushButton_1_6.setObjectName(u"pushButton_1_6")
        self.pushButton_1_6.setGeometry(QRect(330, 400, 99, 31))
        self.pushButton_1_6.setFont(font1)
        self.pushButton_1_5 = QPushButton(Dialog)
        self.pushButton_1_5.setObjectName(u"pushButton_1_5")
        self.pushButton_1_5.setGeometry(QRect(330, 350, 99, 31))
        self.pushButton_1_5.setFont(font1)
        self.pushButton_1_8 = QPushButton(Dialog)
        self.pushButton_1_8.setObjectName(u"pushButton_1_8")
        self.pushButton_1_8.setGeometry(QRect(330, 500, 99, 31))
        self.pushButton_1_8.setFont(font1)
        self.pushButton_1_2 = QPushButton(Dialog)
        self.pushButton_1_2.setObjectName(u"pushButton_1_2")
        self.pushButton_1_2.setGeometry(QRect(330, 200, 99, 31))
        self.pushButton_1_2.setFont(font1)
        self.pushButton_1_9 = QPushButton(Dialog)
        self.pushButton_1_9.setObjectName(u"pushButton_1_9")
        self.pushButton_1_9.setGeometry(QRect(330, 550, 99, 31))
        self.pushButton_1_9.setFont(font1)
        self.pushButton_1_4 = QPushButton(Dialog)
        self.pushButton_1_4.setObjectName(u"pushButton_1_4")
        self.pushButton_1_4.setGeometry(QRect(330, 300, 99, 31))
        self.pushButton_1_4.setFont(font1)
        self.pushButton_1_1 = QPushButton(Dialog)
        self.pushButton_1_1.setObjectName(u"pushButton_1_1")
        self.pushButton_1_1.setGeometry(QRect(330, 150, 99, 31))
        self.pushButton_1_1.setFont(font)
        self.pushButton_1_1.setCheckable(False)
        self.pushButton_1_3 = QPushButton(Dialog)
        self.pushButton_1_3.setObjectName(u"pushButton_1_3")
        self.pushButton_1_3.setGeometry(QRect(330, 250, 99, 31))
        self.pushButton_1_3.setFont(font1)
        self.pushButton_1_7 = QPushButton(Dialog)
        self.pushButton_1_7.setObjectName(u"pushButton_1_7")
        self.pushButton_1_7.setGeometry(QRect(330, 450, 99, 31))
        self.pushButton_1_7.setFont(font1)
        self.pushButton_10_1 = QPushButton(Dialog)
        self.pushButton_10_1.setObjectName(u"pushButton_10_1")
        self.pushButton_10_1.setGeometry(QRect(330, 600, 99, 31))
        self.pushButton_10_1.setFont(font1)
        self.pushButton_10_2 = QPushButton(Dialog)
        self.pushButton_10_2.setObjectName(u"pushButton_10_2")
        self.pushButton_10_2.setGeometry(QRect(330, 650, 99, 31))
        self.pushButton_10_2.setFont(font1)
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(290, -10, 981, 821))
        self.label_12.setPixmap(QPixmap(u"Downloads/robotpic.png"))
        self.line_3 = QFrame(Dialog)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(110, 690, 571, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_14 = QLabel(Dialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(450, 150, 31, 31))
        self.label_15 = QLabel(Dialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(450, 200, 31, 31))
        self.label_16 = QLabel(Dialog)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(450, 250, 31, 31))
        self.label_17 = QLabel(Dialog)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(450, 350, 31, 31))
        self.label_18 = QLabel(Dialog)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(450, 400, 31, 31))
        self.label_19 = QLabel(Dialog)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(450, 300, 31, 31))
        self.label_20 = QLabel(Dialog)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(450, 500, 31, 31))
        self.label_21 = QLabel(Dialog)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(450, 550, 31, 31))
        self.label_22 = QLabel(Dialog)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(450, 450, 31, 31))
        self.label_23 = QLabel(Dialog)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(450, 650, 31, 31))
        self.label_25 = QLabel(Dialog)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(450, 600, 31, 31))
        self.savebutton = QPushButton(Dialog)
        self.savebutton.setObjectName(u"savebutton")
        self.savebutton.setGeometry(QRect(790, 500, 181, 151))
        font2 = QFont()
        font2.setPointSize(18)
        font2.setBold(True)
        font2.setWeight(75)
        self.savebutton.setFont(font2)
        self.label_12.raise_()
        self.calendarWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.horizontalSlider.raise_()
        self.dial.raise_()
        self.spinBox.raise_()
        self.spinBox_2.raise_()
        self.spinBox_3.raise_()
        self.spinBox_4.raise_()
        self.spinBox_5.raise_()
        self.spinBox_6.raise_()
        self.spinBox_7.raise_()
        self.spinBox_8.raise_()
        self.spinBox_9.raise_()
        self.spinBox_10.raise_()
        self.spinBox_11.raise_()
        self.line_2.raise_()
        self.pushButton_1_6.raise_()
        self.pushButton_1_5.raise_()
        self.pushButton_1_8.raise_()
        self.pushButton_1_2.raise_()
        self.pushButton_1_9.raise_()
        self.pushButton_1_4.raise_()
        self.pushButton_1_1.raise_()
        self.pushButton_1_3.raise_()
        self.pushButton_1_7.raise_()
        self.pushButton_10_1.raise_()
        self.pushButton_10_2.raise_()
        self.line_3.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        self.savebutton.raise_()
        self.spinBox.setMaximum(100000)
        self.spinBox.setMinimum(-100000)
        self.spinBox_2.setMaximum(100000)
        self.spinBox_2.setMinimum(-100000)
        self.spinBox_3.setMaximum(100000)
        self.spinBox_3.setMinimum(-100000)
        self.spinBox_4.setMaximum(100000)
        self.spinBox_4.setMinimum(-100000)
        self.spinBox_5.setMaximum(100000)
        self.spinBox_5.setMinimum(-100000)
        self.spinBox_6.setMaximum(100000)
        self.spinBox_6.setMinimum(-100000)
        self.spinBox_7.setMaximum(100000)
        self.spinBox_7.setMinimum(-100000)
        self.spinBox_8.setMaximum(100000)
        self.spinBox_8.setMinimum(-100000)
        self.spinBox_9.setMaximum(100000)
        self.spinBox_9.setMinimum(-100000)
        self.spinBox_10.setMaximum(100000)
        self.spinBox_10.setMinimum(-100000)
        self.spinBox_11.setMaximum(100000)
        self.spinBox_11.setMinimum(-100000)
        self.pushButton.clicked.connect(self.decrease_value1)
        self.pushButton_1_1.clicked.connect(self.increase_value1)
        self.pushButton_2.clicked.connect(self.decrease_value2)
        self.pushButton_1_2.clicked.connect(self.increase_value2)
        self.pushButton_3.clicked.connect(self.decrease_value3)
        self.pushButton_1_3.clicked.connect(self.increase_value3)
        self.pushButton_4.clicked.connect(self.decrease_value4)
        self.pushButton_1_4.clicked.connect(self.increase_value4)
        self.pushButton_5.clicked.connect(self.decrease_value5)
        self.pushButton_1_5.clicked.connect(self.increase_value5)
        self.pushButton_6.clicked.connect(self.decrease_value6)
        self.pushButton_1_6.clicked.connect(self.increase_value6)
        self.pushButton_7.clicked.connect(self.decrease_value7)
        self.pushButton_1_7.clicked.connect(self.increase_value7)
        self.pushButton_8.clicked.connect(self.decrease_value8)
        self.pushButton_1_8.clicked.connect(self.increase_value8)
        self.pushButton_9.clicked.connect(self.decrease_value9)
        self.pushButton_1_9.clicked.connect(self.increase_value9)
        self.pushButton_10.clicked.connect(self.decrease_value10)
        self.pushButton_10_1.clicked.connect(self.increase_value10)
        self.pushButton_11.clicked.connect(self.decrease_value11)
        self.pushButton_10_2.clicked.connect(self.increase_value11)
        self.savebutton.clicked.connect(self.save_values_to_text_file)
        self.retranslateUi(Dialog)
        
        QMetaObject.connectSlotsByName(Dialog)
        
    def save_values_to_text_file(self):
        # 텍스트 파일 경로 설정
        file_path = '/home/irobot/save.txt'

        # 모든 SpinBox의 값 가져오기
        spin_boxes = [self.spinBox, self.spinBox_2, self.spinBox_3, self.spinBox_4, self.spinBox_5,
                      self.spinBox_6, self.spinBox_7, self.spinBox_8, self.spinBox_9, self.spinBox_10, self.spinBox_11]

        # 텍스트 파일에 값을 저장
        with open(file_path, 'w') as file:
            for spinBox in spin_boxes:
                value = str(spinBox.value())
                file.write(value + '\n')

        print(f"파일 '{file_path}'을 라즈베리 파이에 저장했습니다.")
    # setupUi
    def decrease_value1(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox.value()
        self.spinBox.setValue(current_value - 500)

    def increase_value1(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox.value()
        self.spinBox.setValue(current_value + 500)
        
    def decrease_value2(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_2.value()
        self.spinBox_2.setValue(current_value - 500)

    def increase_value2(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_2.value()
        self.spinBox_2.setValue(current_value + 500)
    
    def decrease_value3(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_3.value()
        self.spinBox_3.setValue(current_value - 500)

    def increase_value3(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_3.value()
        self.spinBox_3.setValue(current_value + 500)
    def decrease_value4(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_4.value()
        self.spinBox_4.setValue(current_value - 500)

    def increase_value4(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_4.value()
        self.spinBox_4.setValue(current_value + 500)
        
    def decrease_value5(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_5.value()
        self.spinBox_5.setValue(current_value - 500)

    def increase_value5(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_5.value()
        self.spinBox_5.setValue(current_value + 500)
        
    def decrease_value6(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_6.value()
        self.spinBox_6.setValue(current_value - 500)

    def increase_value6(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_6.value()
        self.spinBox_6.setValue(current_value + 500)
    
    def decrease_value7(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_7.value()
        self.spinBox_7.setValue(current_value - 500)

    def increase_value7(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_7.value()
        self.spinBox_7.setValue(current_value + 500)
        
    def decrease_value8(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_8.value()
        self.spinBox_8.setValue(current_value - 500)

    def increase_value8(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_8.value()
        self.spinBox_8.setValue(current_value + 500)
        
    def decrease_value9(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_9.value()
        self.spinBox_9.setValue(current_value - 500)

    def increase_value9(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_9.value()
        self.spinBox_9.setValue(current_value + 500)
        
    def decrease_value10(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_10.value()
        self.spinBox_10.setValue(current_value - 500)

    def increase_value10(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_10.value()
        self.spinBox_10.setValue(current_value + 500)
    
    def decrease_value11(self):
        # SpinBox의 값에서 500을 뺀다.
        current_value = self.spinBox_11.value()
        self.spinBox_11.setValue(current_value - 500)

    def increase_value11(self):
        # SpinBox의 값에 500을 더한다.
        current_value = self.spinBox_11.value()
        self.spinBox_11.setValue(current_value + 500)
        
    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; text-decoration: underline; color:#04295a;\">INTERACTIVE ROBOTICS LAB</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uc784\uc218\ucca0</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uc774\ub3d9\ud55c</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uc774\uac15\uc6d0</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uc724\uac15\uc77c</span></p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uae40\uc131\uc6a9</span></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uc815\uc720\uc9c4</span></p><p><br/></p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\ud558\uc2b9\ud604</span></p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uc591\uc815\ud658</span></p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uc815\ud0dc\uc218</span></p></body></html>", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\uc190\uc601\ucc44</span></p><p><br/></p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">\ubc31\uc2b9\uc6b0</span></p></body></html>", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_3.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_4.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_5.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_6.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_7.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_8.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_9.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_10.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_11.setText(QCoreApplication.translate("Dialog", u"\uad6c\uc785", None))
        self.pushButton_1_6.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_1_5.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_1_8.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_1_2.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_1_9.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_1_4.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_1_1.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_1_3.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_1_7.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_10_1.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.pushButton_10_2.setText(QCoreApplication.translate("Dialog", u"\ucde8\uc18c", None))
        self.label_12.setText("")
        self.label_14.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_21.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"\uc794\uc561", None))
        self.savebutton.setText(QCoreApplication.translate("Dialog", u"\uc815\uc0b0\ud558\uae30", None))
    # retranslateUi

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
